import { useState, useEffect } from 'react';
import { Search, MapPin, DollarSign, Clock, Users, BookOpen, ChevronRight, X } from 'lucide-react';
import { LoadingCenter, Modal, StatusBadge, EmptyState } from '../../components/shared/UI';
import { fmtSalary, fmtDate, parseArr } from '../../utils/helpers';
import api from '../../utils/api';
import toast from 'react-hot-toast';

export default function StudentJobs() {
  const [jobs, setJobs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState(null);
  const [applying, setApplying] = useState(false);
  const [coverLetter, setCoverLetter] = useState('');
  const [applied, setApplied] = useState(new Set());
  const [genLoading, setGenLoading] = useState(false);

  useEffect(() => {
    api.get('/jobs').then(d => setJobs(d)).catch(() => {}).finally(() => setLoading(false));
    api.get('/applications/mine').then(d => setApplied(new Set(d.map(a => a.job_id)))).catch(() => {});
  }, []);

  const filtered = jobs.filter(j =>
    !search || j.title.toLowerCase().includes(search.toLowerCase()) ||
    j.company_name?.toLowerCase().includes(search.toLowerCase()) ||
    j.location?.toLowerCase().includes(search.toLowerCase())
  );

  const apply = async () => {
    if (!selected) return;
    setApplying(true);
    try {
      await api.post('/applications', { jobId: selected.id, coverLetter });
      setApplied(s => new Set([...s, selected.id]));
      setSelected(null); setCoverLetter('');
      toast.success('Application submitted! 🎉');
    } catch (e) { toast.error(e.error || 'Apply failed'); }
    finally { setApplying(false); }
  };

  const genCoverLetter = async () => {
    if (!selected) return;
    setGenLoading(true);
    try {
      const resumeText = `Skills: ${JSON.stringify(parseArr(selected.required_skills))}. Looking for opportunities in ${selected.title} role.`;
      const d = await api.post('/ai/cover-letter', { resumeText, jobDescription: selected.description, companyName: selected.company_name, jobTitle: selected.title });
      setCoverLetter(d.coverLetter);
      toast.success('Cover letter generated by AI ✨');
    } catch (e) { toast.error('Generation failed'); }
    finally { setGenLoading(false); }
  };

  if (loading) return <LoadingCenter />;

  return (
    <div>
      <div className="section-header">
        <div>
          <h1 className="page-title">Browse Jobs</h1>
          <p className="page-sub">{filtered.length} opportunities available</p>
        </div>
      </div>

      {/* Search */}
      <div className="input-with-icon" style={{ marginBottom: 20, maxWidth: 480 }}>
        <Search size={15} className="input-icon" />
        <input className="input" placeholder="Search jobs, companies, locations…" value={search} onChange={e => setSearch(e.target.value)} />
      </div>

      {filtered.length === 0 ? (
        <EmptyState icon="🔍" title="No jobs found" desc="Try a different search or check back later." />
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {filtered.map(job => {
            const skills = parseArr(job.required_skills);
            const branches = parseArr(job.eligible_branches);
            const isApplied = applied.has(job.id);
            return (
              <div key={job.id} className="card card-p" style={{ cursor: 'pointer' }} onClick={() => setSelected(job)}>
                <div style={{ display: 'flex', gap: 14, alignItems: 'flex-start' }}>
                  <div className="company-logo" style={{ width: 48, height: 48, fontSize: 20 }}>{(job.company_name || 'C')[0]}</div>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10, flexWrap: 'wrap' }}>
                      <div>
                        <div className="job-title">{job.title}</div>
                        <div className="job-company" style={{ marginBottom: 8 }}>{job.company_name} · {job.industry}</div>
                      </div>
                      {isApplied
                        ? <span className="badge badge-green">Applied ✓</span>
                        : <span className="btn btn-primary btn-sm" style={{ pointerEvents: 'none' }}>Apply →</span>}
                    </div>
                    <div className="job-meta" style={{ marginBottom: 10 }}>
                      {job.location && <span className="job-meta-item"><MapPin size={12} /> {job.location}</span>}
                      <span className="job-meta-item">💰 {fmtSalary(job.salary_min, job.salary_max)}</span>
                      <span className="job-meta-item"><Clock size={12} /> Deadline: {fmtDate(job.application_deadline)}</span>
                      <span className="job-meta-item"><Users size={12} /> {job.slots} slot{job.slots !== 1 ? 's' : ''}</span>
                      {job.min_cgpa > 0 && <span className="job-meta-item">Min CGPA: {job.min_cgpa}</span>}
                    </div>
                    <div className="tags-row">
                      {skills.slice(0, 5).map(s => <span key={s} className="tag">{s}</span>)}
                      {branches.slice(0, 2).map(b => <span key={b} className="tag" style={{ background: 'var(--accent-bg)', color: 'var(--accent)' }}>{b}</span>)}
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Job detail / apply modal */}
      <Modal open={!!selected} onClose={() => setSelected(null)} title={selected?.title || ''} size="lg"
        footer={
          selected && (
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%' }}>
              <span style={{ fontSize: 13, color: 'var(--text-2)' }}>{selected.company_name}</span>
              <div style={{ display: 'flex', gap: 10 }}>
                <button className="btn btn-secondary" onClick={() => setSelected(null)}>Cancel</button>
                {applied.has(selected?.id)
                  ? <button className="btn btn-success" disabled>Applied ✓</button>
                  : <button className="btn btn-primary" onClick={apply} disabled={applying}>{applying ? <><div className="spinner spinner-sm" style={{ borderTopColor:'#fff' }}/> Applying…</> : 'Submit Application'}</button>}
              </div>
            </div>
          )
        }>
        {selected && (() => {
          const skills = parseArr(selected.required_skills);
          const branches = parseArr(selected.eligible_branches);
          const batches = parseArr(selected.eligible_batches);
          return (
            <div>
              <div style={{ display: 'flex', gap: 14, marginBottom: 18 }}>
                <div className="company-logo" style={{ width: 52, height: 52, fontSize: 22 }}>{(selected.company_name||'C')[0]}</div>
                <div>
                  <div style={{ fontWeight: 600, fontSize: 16 }}>{selected.title}</div>
                  <div style={{ color: 'var(--text-2)', fontSize: 14 }}>{selected.company_name}</div>
                  <div className="job-meta" style={{ marginTop: 4 }}>
                    {selected.location && <span><MapPin size={12} /> {selected.location}</span>}
                    <span>💰 {fmtSalary(selected.salary_min, selected.salary_max)}</span>
                    <span>Deadline: {fmtDate(selected.application_deadline)}</span>
                  </div>
                </div>
              </div>

              <hr className="divider" />
              <div style={{ fontWeight: 600, marginBottom: 6 }}>Job Description</div>
              <p style={{ fontSize: 14, color: 'var(--text-2)', lineHeight: 1.7, marginBottom: 16 }}>{selected.description}</p>

              <div className="grid-2" style={{ marginBottom: 16 }}>
                <div>
                  <div style={{ fontWeight: 600, fontSize: 13, marginBottom: 6 }}>Required Skills</div>
                  <div className="tags-row">{skills.map(s => <span key={s} className="tag">{s}</span>)}</div>
                </div>
                <div>
                  <div style={{ fontWeight: 600, fontSize: 13, marginBottom: 6 }}>Eligibility</div>
                  <div style={{ fontSize: 13, color: 'var(--text-2)' }}>
                    {selected.min_cgpa > 0 && <div>Min CGPA: {selected.min_cgpa}</div>}
                    {branches.length > 0 && <div>Branches: {branches.join(', ')}</div>}
                    {batches.length > 0 && <div>Batch: {batches.join(', ')}</div>}
                  </div>
                </div>
              </div>

              {!applied.has(selected.id) && (
                <>
                  <hr className="divider" />
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
                    <label className="label" style={{ margin: 0 }}>Cover Letter <span style={{ color: 'var(--text-3)', fontWeight: 400 }}>(optional)</span></label>
                    <button className="btn btn-secondary btn-sm" onClick={genCoverLetter} disabled={genLoading}>
                      {genLoading ? <><div className="spinner spinner-sm" /> Generating…</> : '✨ AI Generate'}
                    </button>
                  </div>
                  <textarea className="input" rows={5} placeholder="Write your cover letter, or use AI to generate one…" value={coverLetter} onChange={e => setCoverLetter(e.target.value)} />
                </>
              )}
            </div>
          );
        })()}
      </Modal>
    </div>
  );
}
